pipeline {
    agent any
    tools {
        go 'go-1.17'
    }
    environment {
        GO111MODULE='on'
    }
    stages {
        stage('test') {
            steps {
                git 'https://github.com/sofackj/go-webapp-sample.git'
                sh 'go test ./...'
            }
        }
        stage('build') {
            steps {
                git 'https://github.com/sofackj/go-webapp-sample.git'
                sh 'go build .'
            }
        }
        stage('un') {
            steps {
                sh 'go test ./...'
            }
        }
    }
}